### ISSUE TITLE
Future: 色图不够色

### ISSUE THREAD

**Issue by kexue-z** [lgc-NB2Dev/nonebot-plugin-color#1]
- 我想要五彩斑斓的黑和五颜六色白

- 你这个就一种颜色 完全不够色！

- 建议：添加多种色图生产并导出色号，比如 [这](https://uigradients.com/#SolidVault) 种

~~又拿下第一个issue了~~

**Comment by monsterxcn** [comment]
懂了，先把渐变色加个 TODO！

然后你要的导出色号是什么？渐变色不要显示 hex 要显示 `#SolidVault` 这样吗？

**Comment by kexue-z** [comment]
css的那种格式就好

**Comment by wjzlyr** [comment]
为什么安装后用不了呀QAQ
![image](https://user-images.githubusercontent.com/58624426/186938475-eed9c16d-4007-4033-89b3-9741b060847a.png)

**Comment by lgc2333** [comment]
现在看看够不够色
