### ISSUE TITLE
显示色号，文字颜色只使用黑色或白色！

### ISSUE THREAD

**Issue by Rain-0x01-39** [lgc-NB2Dev/nonebot-plugin-color#6]
![Image_1725076690401](https://github.com/user-attachments/assets/63f29606-04bb-4bec-b179-acda51c97ff5)

现在图片上的文字是输入颜色的反转颜色，不是很美观，我的想法是亮色文字使用黑色，暗色文字使用白色

**Comment by lgc2333** [comment]
https://github.com/lgc-NB2Dev/nonebot-plugin-color/commit/bff1b750b55ffb6aa643a06051020524d9087588
